definitions:
  users.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /users/create:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя
      parameters:
      - description: Имя пользователя
        in: query
        name: name
        type: string
      - description: Эмейл пользователя
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Создать пользователя
      tags:
      - users
  /users/get:
    get:
      consumes:
      - application/json
      description: Если userId указан, возвращает одного пользователя, иначе — всех
        пользователей
      parameters:
      - description: ID пользователя
        in: query
        name: userId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Получить пользователей или одного пользователя
      tags:
      - users
  /users/update:
    put:
      consumes:
      - application/json
      description: Обновляет поля пользователя
      parameters:
      - description: Новое имя пользователя
        in: query
        name: name
        type: string
      - description: Новый эмейл пользователя
        in: query
        name: email
        type: string
      - description: ID пользователя
        in: query
        name: userId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
      summary: Обновить пользователя
      tags:
      - users
swagger: "2.0"
